import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Carrito",
  description: "Generated by create next app",
};


export default function MostradorPage() {
  
    return (
      <div className="flex flex-col items-center justify-center w-full h-screen">
        <span>Todavia no seleccionas algun producto para saber más acerca de el.</span>     
        
      </div>
    );
  }